import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { bip39Module, deriveRecoveryKey, hashMnemonic } from '../../crypto/bip39'
import { keysModule, toBase64 } from '../../crypto/keys'
import { authApi } from '../../api/auth'
import { usersApi } from '../../api/users'
import { settingsApi } from '../../api/settings'
import { useAuthStore } from '../../store/auth'
import { requireCek } from '../../store/unlock'
import Button from '../../components/ui/Button'
import { Copy, CheckCircle, FileDown } from 'lucide-react'

function downloadRecoveryPdf(words: string[]) {
  // Use jsPDF to generate a printable recovery phrase document (T10/Phase 4)
  import('jspdf').then(({ jsPDF }) => {
    const doc = new jsPDF()
    const BRAND = '#3D4F6B'

    // Header
    doc.setFillColor(BRAND)
    doc.rect(0, 0, 210, 30, 'F')
    doc.setTextColor('#ffffff')
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text('Legate — Recovery Phrase', 14, 20)

    // Warning
    doc.setTextColor('#92400e')
    doc.setFillColor('#fffbeb')
    doc.rect(10, 36, 190, 18, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text(
      '⚠ KEEP THIS DOCUMENT SECURE. Anyone with these 24 words can access your vault.',
      14,
      44,
      { maxWidth: 182 },
    )
    doc.text(
      'Do not store digitally. Write it down or print and store in a secure, offline location.',
      14,
      50,
      { maxWidth: 182 },
    )

    // 24-word grid — 4 columns × 6 rows
    doc.setTextColor('#0d1117')
    doc.setFontSize(11)
    const colW = 46
    const rowH = 14
    const startX = 14
    const startY = 66

    words.forEach((word, i) => {
      const col = i % 4
      const row = Math.floor(i / 4)
      const x = startX + col * colW
      const y = startY + row * rowH

      // Numbered box
      doc.setFillColor('#f1f5f9')
      doc.roundedRect(x, y - 7, colW - 2, 12, 2, 2, 'F')
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(7)
      doc.setTextColor('#6b7280')
      doc.text(`${i + 1}`, x + 2, y - 1)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(10)
      doc.setTextColor('#0d1117')
      doc.text(word, x + 2, y + 3)
    })

    // Footer disclaimer
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor('#9ca3af')
    doc.text(
      'This document was generated by Legate. It is not a legal will or official document.',
      14,
      175,
      { maxWidth: 182 },
    )
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 181)

    doc.save('legate-recovery-phrase.pdf')
  }).catch(() => {
    // jsPDF not available — fall back to clipboard copy
    navigator.clipboard.writeText(words.join(' ')).catch(() => {})
    alert('PDF export failed. Your phrase has been copied to clipboard.')
  })
}

export default function StepRecovery() {
  const navigate = useNavigate()
  const authStore = useAuthStore()
  const [words, setWords] = useState<string[]>([])
  const [checked, setChecked] = useState(false)
  const [copied, setCopied] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    setWords(bip39Module.generatePhrase())
  }, [])

  const handleCopy = async () => {
    await navigator.clipboard.writeText(words.join(' '))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleReady = async () => {
    setLoading(true)
    setError(null)
    try {
      const cek = await requireCek()
      const mnemonic = words.join(' ')
      const salt = crypto.getRandomValues(new Uint8Array(16))
      const recoveryKey = await deriveRecoveryKey(mnemonic, salt)
      const { encryptedCek, iv } = await keysModule.encryptCEK(cek, recoveryKey)
      const recoveryPhraseHash = await hashMnemonic(mnemonic)

      await authApi.setRecoveryKey({
        recovery_encrypted_cek: toBase64(encryptedCek),
        recovery_cek_iv: toBase64(iv),
        recovery_salt: toBase64(salt),
        recovery_phrase_hash: recoveryPhraseHash,
      })

      // T5: clear onboarding flag
      await settingsApi.patchSettings({ setup_step: 0, needs_onboarding: false }).catch(() => {})
      try {
        await usersApi.update({ needs_onboarding: false })
      } catch { /* non-critical */ }
      authStore.setNeedsOnboarding(false)
      navigate('/vault')
    } catch {
      setError('Could not save your recovery phrase. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-md mx-auto px-4 pb-8">
      <div className="bg-white rounded-2xl shadow-lg p-8">
        <h1 className="text-2xl font-bold text-[#0D1117] mb-2">Your Recovery Phrase</h1>
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-6">
          <p className="text-sm text-amber-800 font-medium">
            ⚠️ Write this down. You cannot recover your capsules without it. This phrase is shown only once.
          </p>
        </div>

        <div className="grid grid-cols-4 gap-2 mb-4">
          {words.map((word, i) => (
            <div key={i} className="bg-slate-50 rounded-lg p-2 text-center">
              <p className="text-xs text-[#6B7280] mb-0.5">{i + 1}</p>
              <p className="text-sm font-medium text-[#0D1117]">{word}</p>
            </div>
          ))}
        </div>

        <div className="flex gap-2 mb-6">
          <button
            onClick={handleCopy}
            className="flex-1 py-2 border border-gray-200 rounded-xl text-sm font-medium text-[#3D4F6B] hover:bg-gray-50 flex items-center justify-center gap-2"
          >
            {copied ? <CheckCircle className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
          <button
            onClick={() => downloadRecoveryPdf(words)}
            className="flex-1 py-2 border border-gray-200 rounded-xl text-sm font-medium text-[#3D4F6B] hover:bg-gray-50 flex items-center justify-center gap-2"
          >
            <FileDown className="w-4 h-4" />
            Download PDF
          </button>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-3 mb-4">
            <p className="text-sm text-red-700">{error}</p>
          </div>
        )}

        <label className="flex items-start gap-3 mb-6 cursor-pointer">
          <input
            type="checkbox"
            checked={checked}
            onChange={e => setChecked(e.target.checked)}
            className="mt-0.5 w-4 h-4 accent-[#3D4F6B]"
          />
          <span className="text-sm text-[#0D1117]">
            I have written down my recovery phrase and stored it somewhere safe.
          </span>
        </label>

        <Button fullWidth disabled={!checked} loading={loading} onClick={handleReady}>
          I'm Ready
        </Button>
      </div>
    </div>
  )
}
